[phases.install]
cmds = [
  "npm install --prefix server",
  "env -u NODE_ENV npm install --prefix client"
]

[phases.build]
cmds = [
  "npm run build --prefix client"
]

[start]
cmd = "cd server && npx prisma generate && npx prisma db push && node server.js"
