[phases.install]
cmds = [
  "npm install --prefix server",
  "npm install --include=dev --prefix client"
]

[phases.build]
cmds = [
  "(cd server && npx prisma generate)",
  "npm run build --prefix client"
]

[start]
cmd = "cd server && npx prisma db push && node server.js"
